spring.application.name=movie-catalog-service

server.port=8081



# Enable specific endpoints
management.endpoints.web.exposure.include=health,info,circuitbreakers


# Enable health details (shows full info instead of just "UP")
management.endpoint.health.show-details=always
