spring.application.name=movie-catalog-service

server.port=8081



# Enable specific endpoints
management.endpoints.web.exposure.include=health,info,circuitbreakers


# Enable health details (shows full info instead of just "UP")
management.endpoint.health.show-details=always

resilience4j.thread-pool-bulkhead.instances.movieCatalogService.max-thread-pool-size=10
resilience4j.thread-pool-bulkhead.instances.movieCatalogService.core-thread-pool-size=5
resilience4j.thread-pool-bulkhead.instances.movieCatalogService.queue-capacity=20
